server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mudi?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: Timaorgs@1910
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect